---
- hosts: opsManager
  remote_user: ec2-user
  tasks:
  - name: get automation apikey
    shell: mongo 127.0.0.1:27017 --quiet --eval "print(db.getSiblingDB('mmsdbconfig').config.customers.findOne().k)"
    register: opsmanager_apikey
  - debug: var=opsmanager_apikey
  - name: get automation groupid
    shell: mongo 127.0.0.1:27017 --quiet --eval "print(db.getSiblingDB('mmsdbconfig').config.customers.findOne()._id.str)" 
    register: opsmanager_groupid
  - debug: var=opsmanager_groupid
  - debug: var=opsmanager_apikey
