---
- hosts: opsManager
  remote_user: ec2-user
  become: yes
  vars:
    opsmanagerGPG: mongodb-mms-3.4.3.402-1.x86_64.rpm.gpg
    opsmanager: mongodb-mms-3.4.3.402-1.x86_64.rpm
  tasks:
  - get_url: url=https://s3.amazonaws.com/mlynn/{{opsmanagerGPG}} dest=/home/ec2-user/{{opsmanagerGPG}}
  - shell: echo 1234 | gpg --batch --passphrase-fd 0 {{opsmanagerGPG}}
  - yum: name=/home/ec2-user/{{opsmanager}} state=present
  - service: name=mongodb-mms state=started
