---
- hosts: opsManager
  remote_user: ec2-user
  become: yes
  tasks:
  - template: src=../files/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode="u=rw,g=r,o=r"
  - yum: name=* state=latest
  - yum: name=mongodb-org state=latest
  - yum: name=mongodb-org-shell state=latest
  - yum: name=gpg state=latest
  - file: path=/data state=directory mode=0755 owner=mongod group=mongod
  - file: path=/data/appdb state=directory mode=0755 owner=mongod group=mongod
  - file: path=/data/backup state=directory mode=0755 owner=mongod group=mongod
