---
- hosts: ReplicaSet,opsManager
  remote_user: ec2-user
  gather_facts: false
  become: true
  tasks:
  - name: disable hugepage support
    shell: /bin/echo never | /usr/bin/sudo /usr/bin/tee /sys/kernel/mm/transparent_hugepage/enabled 
  - name: disable hugepage defrag
    shell: /bin/echo never | /usr/bin/sudo /usr/bin/tee /sys/kernel/mm/transparent_hugepage/defrag
  - service: name=mongod state=restarted


